#!/bin/sh

# locker Start/Stop script for Locker Enterprise
#
# chkconfig: 2345 99 08

. /etc/rc.d/init.d/functions

HOME_PATH=/opt/sniffer
DAEMON_PROG=$HOME_PATH/sniffer
PID_FILE=$HOME_PATH/sniffer.pid
STOP_TIMEOUT=120

start() {
  echo -n "Starting ${DAEMON_PROG##*/}: ";
  cd $HOME_PATH
  $DAEMON_PROG -i eth1 not host 10.1.1.82 and not host 10.1.1.83 and not host 10.1.1.84 and not host 10.1.1.85 and not host 10.1.1.86 and not host 10.1.1.87 and not host 10.1.1.88 and not host 10.1.1.91 and not host 10.1.1.92 and not host 10.1.1.93 and not host 10.1.1.125 and not host 10.1.1.128 and not host 10.1.1.5 and not host 10.1.1.25 >> $HOME_PATH/log/sniffer.log 2>/dev/null &
  pid="$!"
  RETVAL=$?
  [ $RETVAL = 0   ] && success && echo $pid > $PID_FILE
  [ $RETVAL != 0   ] && failure && rm -f $PID_FILE
  echo
  return $RETVAL;
}

stop() {
  echo -n "Stopping ${DAEMON_PROG##*/}: ";
  killproc -p ${PID_FILE} -d ${STOP_TIMEOUT} ${DAEMON_PROG}
  RETVAL=$?
  [ $RETVAL = 0   ] && success && rm -f $PID_FILE
  [ $RETVAL != 0   ] && failure
  echo
  return $RETVAL
}

case "$1" in
  start)
    start
    ;;  
  stop)
    stop
    ;;  
  restart)
    stop
    start
    ;;  
  *)  
    echo "Usage $0 {start | stop | restart}"
    RETVAL=2
esac

exit $RETVAL
